name: contentblocks/bttabstoaccordion
title: contentblocks/bttabstoaccordion
description: 'Tabs to Accordion mit Bootstrap 5.3'
saveAndClose: true
prefixFields: true
prefixType: full
basics:
  - contentblocks/Accordionsettings
  - contentblocks/Tabssettings
  - contentblocks/Appearance
  - contentblocks/Links
group: ContentBlocks
fields:
  - identifier: backendheader
    label: Pluginbeschreibung für TYPO3 BE
    type: Text
  - identifier: tab_2
    type: Tab
    label: Tab/Accordion Items
  - identifier: palette_42
    type: Palette
  - identifier: tabtoaccordionsets
    type: Collection
    label: Einzelne TabToAccordionitem anlegen
    foreign_table: tt_content
    allowedRecordTypes:
      - contentblocks_textimage